"""empty message

Revision ID: 68cd61de3f61
Revises: e9afa0903010
Create Date: 2019-02-11 21:45:06.752887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68cd61de3f61'
down_revision = 'e9afa0903010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('complete', sa.Boolean(), nullable=False))
    op.drop_column('item', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('item', 'complete')
    # ### end Alembic commands ###
